[package]
name = "st25r3916"
version = "0.1.0"
description = "ST25R3916 NFC transceiver driver (Initiator & Target/Card Emulation)"
readme = "README.md"
publish = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true

[dev-dependencies]
embedded-hal-mock.workspace = true

[lints]
workspace = true
