[package]
name = "m5stack-papermono"
version = "0.1.0"
description = "Board support for M5Stack PaperMono (C153): Lite nets plus NFC and LoRa"
readme = "README.md"
publish = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
m5stack-papermono-lite = { path = "../m5stack-papermono-lite", version = "0.1.0" }

[lints]
workspace = true
