[package]
name = "m5pm1"
version = "0.1.0"
description = "M5PM1 PMIC register map and I2C access (PWM0, ADC, system)"
readme = "README.md"
publish = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
embedded-hal.workspace = true

[dev-dependencies]
embedded-hal-mock.workspace = true

[lints]
workspace = true
